services:
  app:
    image: todo_front_dev
    container_name: todo_front_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://localhost:3000/
  debug-helper:
    image: busybox

volumes:
  node_modules:
